services:
  - type: web
    name: zomage
    env: dotnet
    buildCommand: dotnet publish -c Release -o ./publish
    startCommand: cd ./publish && dotnet zomage.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:10000

